version: "3.8"
services:
  config-server:
    restart: unless-stopped
    image: bjoggis/config-server:v4
    container_name: config-server
    environment:
      - SPRING_PROFILES_ACTIVE=prod
      - ENCRYPT_KEY=$ENCRYPT_KEY
      - SPRING_CLOUD_CONFIG_JDBC_URL=$SPRING_CLOUD_CONFIG_JDBC_URL
      - SPRING_CLOUD_CONFIG_JDBC_USERNAME=$SPRING_CLOUD_CONFIG_JDBC_USERNAME
      - SPRING_CLOUD_CONFIG_JDBC_PASSWORD=$SPRING_CLOUD_CONFIG_JDBC_PASSWORD
    networks:
      - public
    labels:
      - traefik.enable=true
      - traefik.http.routers.config-server.rule=HostRegexp(`^config\.(jonasandersen.no|bjoggis.com)$`)
      - traefik.http.routers.config-server.entrypoints=http,https
      - traefik.http.services.config-server.loadbalancer.server.port=8888
networks:
  public:
    external: true
