version: "3.8"
services:
  uptime-kuma:
    restart: unless-stopped
    image: louislam/uptime-kuma:1
    ports:
      - 3001:3001
    volumes:
      - /opt/dockge-stuff/uptimekuma:/app/data
    networks:
      - public
networks:
  public:
    external: true
