version: "3.8"
services:
  grafana:
    image: grafana/grafana-oss:11.5.2
    container_name: grafana
    volumes:
      - /mnt/data/grafana:/var/lib/grafana
    restart: unless-stopped
    networks:
      - public
    labels:
      - traefik.enable=true
      - traefik.http.routers.grafana.rule=(Host(`grafana.jonasandersen.no`) ||
        Host(`grafana.jonasandersen.dev`))
      - traefik.http.services.grafana.loadbalancer.server.port=3000
      - traefik.http.routers.grafana.entrypoints=http,https,http-external
    environment:
      - GF_SERVER_ROOT_URL=https://grafana.jonasandersen.no
  prometheus:
    container_name: prometheus
    restart: unless-stopped
    image: prom/prometheus:v2.55.1
    command: --config.file=/etc/prometheus/prometheus.yaml
    volumes:
      - /mnt/data/prometheus/prometheus.yaml:/etc/prometheus/prometheus.yaml:ro
      - /mnt/data/prometheus:/prometheus
    networks:
      - public
    extra_hosts:
      - host.docker.internal:host-gateway
  node_exporter:
    image: prom/node-exporter:v1.8.2
    container_name: node-exporter
    command:
      - --path.rootfs=/host
    network_mode: host
    pid: host
    restart: unless-stopped
    volumes:
      - /:/host:ro,rslave
  loki:
    image: grafana/loki:3.3.0
    ports:
      - 3100:3100
    command: -config.file=/etc/loki/local-config.yaml
    restart: unless-stopped
    networks:
      - public
    volumes:
      - /mnt/data/loki:/loki
networks:
  public:
    external: true
