version: "3.8"
services:
  grafana:
    image: grafana/grafana-oss:10.4.12
    container_name: grafana
    volumes:
      - /opt/dockge-stuff/grafana:/var/lib/grafana
    restart: unless-stopped
    networks:
      - public
    labels:
      - traefik.enable=true
      - traefik.http.routers.grafana.rule=Host(`grafana.jonasandersen.no`)
      - traefik.http.services.grafana.loadbalancer.server.port=3000
      - traefik.http.routers.grafana.entrypoints=http,https
  prometheus:
    container_name: prometheus
    restart: unless-stopped
    image: prom/prometheus:v2.55.1
    command: --config.file=/etc/prometheus/prometheus.yaml
    volumes:
      - /opt/dockge-stuff/prometheus/prometheus.yaml:/etc/prometheus/prometheus.yaml:ro
      - /opt/dockge-stuff/prometheus:/prometheus
    networks:
      - public
    extra_hosts:
    - "host.docker.internal:host-gateway"
  node_exporter:
    image: prom/node-exporter:v1.8.2
    container_name: node-exporter
    command:
      - --path.rootfs=/host
    network_mode: host
    pid: host
    restart: unless-stopped
    volumes:
      - /:/host:ro,rslave
networks:
  public:
    external: true
